# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38ab2ad790348a6b04ce4975076024ec3ea4218cd9ae8a29b0c0688332abe1bf73e6536f807a3e76b99ecd3851beb107d3ee622d59a9fd490aa9773c9c2a3c95

test:
  secret_key_base: a7995ad164521d1b34e56e00ce352f8200ef952683ed9ce4c0657ddebc8ad862527cbc90297b77ba56a7cc3e7d3677c66df42b8a7bf31382c554964a57b7ea36

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
